"""create referrals table

Revision ID: a3e6a5f9c3f8
Revises: 6d5bcb59610c
Create Date: 2026-09-01 16:40:24.620687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3e6a5f9c3f8'
down_revision: Union[str, Sequence[str], None] = '6d5bcb59610c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('encounter_id', sa.UUID(), nullable=False),
    sa.Column('referring_facility_id', sa.UUID(), nullable=False),
    sa.Column('referring_provider_id', sa.Integer(), nullable=False),
    sa.Column('receiving_facility_id', sa.UUID(), nullable=False),
    sa.Column('receiving_provider_id', sa.Integer(), nullable=True),
    sa.Column('referral_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('clinical_summary', sa.Text(), nullable=True),
    sa.Column('requested_specialty', sa.String(length=100), nullable=True),
    sa.Column('requested_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by', sa.Integer(), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_by', sa.Integer(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_by', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=True),
    sa.Column('scheduled_time', sa.Time(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_by', sa.Integer(), nullable=True),
    sa.Column('outcome_status', sa.String(length=100), nullable=True),
    sa.Column('outcome_notes', sa.Text(), nullable=True),
    sa.Column('follow_up_required', sa.Boolean(), nullable=False),
    sa.Column('follow_up_date', sa.Date(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiving_facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiving_provider_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['referring_facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['referring_provider_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rejected_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scheduled_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_encounter_id'), 'referrals', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_referrals_id'), 'referrals', ['id'], unique=False)
    op.create_index(op.f('ix_referrals_patient_id'), 'referrals', ['patient_id'], unique=False)
    op.create_index(op.f('ix_referrals_priority'), 'referrals', ['priority'], unique=False)
    op.create_index(op.f('ix_referrals_receiving_facility_id'), 'referrals', ['receiving_facility_id'], unique=False)
    op.create_index(op.f('ix_referrals_receiving_provider_id'), 'referrals', ['receiving_provider_id'], unique=False)
    op.create_index(op.f('ix_referrals_referring_facility_id'), 'referrals', ['referring_facility_id'], unique=False)
    op.create_index(op.f('ix_referrals_referring_provider_id'), 'referrals', ['referring_provider_id'], unique=False)
    op.create_index(op.f('ix_referrals_requested_specialty'), 'referrals', ['requested_specialty'], unique=False)
    op.create_index(op.f('ix_referrals_status'), 'referrals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referrals_status'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_requested_specialty'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referring_provider_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_referring_facility_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_receiving_provider_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_receiving_facility_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_priority'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_patient_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_encounter_id'), table_name='referrals')
    op.drop_table('referrals')
    # ### end Alembic commands ###
