"""add_fhir_abdm_interoperability_models

Revision ID: ac7c0676af36
Revises: 7db74a1a7f65
Create Date: 2026-09-01 21:52:22.595058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac7c0676af36'
down_revision: Union[str, Sequence[str], None] = '7db74a1a7f65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('consent_artefact_id', sa.String(length=255), nullable=True, comment='ABDM Consent Artefact identifier if issued by external Gateway'),
    sa.Column('purpose', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consents_consent_artefact_id'), 'consents', ['consent_artefact_id'], unique=True)
    op.create_index(op.f('ix_consents_id'), 'consents', ['id'], unique=False)
    op.create_index(op.f('ix_consents_patient_id'), 'consents', ['patient_id'], unique=False)
    op.create_index(op.f('ix_consents_status'), 'consents', ['status'], unique=False)
    op.create_table('interoperability_audits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False, comment='FHIR resourceType or ABDM entity (e.g. Patient, Bundle, Consent)'),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('purpose', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('details', sa.Text(), nullable=True, comment='JSON or contextual event metadata'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interoperability_audits_action'), 'interoperability_audits', ['action'], unique=False)
    op.create_index(op.f('ix_interoperability_audits_id'), 'interoperability_audits', ['id'], unique=False)
    op.create_index(op.f('ix_interoperability_audits_patient_id'), 'interoperability_audits', ['patient_id'], unique=False)
    op.create_index(op.f('ix_interoperability_audits_resource_id'), 'interoperability_audits', ['resource_id'], unique=False)
    op.create_index(op.f('ix_interoperability_audits_timestamp'), 'interoperability_audits', ['timestamp'], unique=False)
    op.create_index(op.f('ix_interoperability_audits_user_id'), 'interoperability_audits', ['user_id'], unique=False)
    op.create_table('patient_identifiers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('system', sa.String(length=255), nullable=False, comment='URI identifying the authority or namespace (e.g. ABDM HealthID)'),
    sa.Column('value', sa.String(length=255), nullable=False, comment='External identifier value (e.g. 14-digit ABHA number or phr@abdm)'),
    sa.Column('identifier_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('system', 'value', name='uq_patient_identifier_system_value')
    )
    op.create_index(op.f('ix_patient_identifiers_id'), 'patient_identifiers', ['id'], unique=False)
    op.create_index(op.f('ix_patient_identifiers_identifier_type'), 'patient_identifiers', ['identifier_type'], unique=False)
    op.create_index(op.f('ix_patient_identifiers_patient_id'), 'patient_identifiers', ['patient_id'], unique=False)
    op.create_index(op.f('ix_patient_identifiers_value'), 'patient_identifiers', ['value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_identifiers_value'), table_name='patient_identifiers')
    op.drop_index(op.f('ix_patient_identifiers_patient_id'), table_name='patient_identifiers')
    op.drop_index(op.f('ix_patient_identifiers_identifier_type'), table_name='patient_identifiers')
    op.drop_index(op.f('ix_patient_identifiers_id'), table_name='patient_identifiers')
    op.drop_table('patient_identifiers')
    op.drop_index(op.f('ix_interoperability_audits_user_id'), table_name='interoperability_audits')
    op.drop_index(op.f('ix_interoperability_audits_timestamp'), table_name='interoperability_audits')
    op.drop_index(op.f('ix_interoperability_audits_resource_id'), table_name='interoperability_audits')
    op.drop_index(op.f('ix_interoperability_audits_patient_id'), table_name='interoperability_audits')
    op.drop_index(op.f('ix_interoperability_audits_id'), table_name='interoperability_audits')
    op.drop_index(op.f('ix_interoperability_audits_action'), table_name='interoperability_audits')
    op.drop_table('interoperability_audits')
    op.drop_index(op.f('ix_consents_status'), table_name='consents')
    op.drop_index(op.f('ix_consents_patient_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_id'), table_name='consents')
    op.drop_index(op.f('ix_consents_consent_artefact_id'), table_name='consents')
    op.drop_table('consents')
    # ### end Alembic commands ###
