"""add facilities appointments and queues

Revision ID: f3d047ed8d2b
Revises: 85a2488d7660
Create Date: 2026-09-01 15:56:52.473425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3d047ed8d2b'
down_revision: Union[str, Sequence[str], None] = '85a2488d7660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('facility_code', sa.String(length=50), nullable=False),
    sa.Column('facility_type', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facilities_facility_code'), 'facilities', ['facility_code'], unique=True)
    op.create_index(op.f('ix_facilities_id'), 'facilities', ['id'], unique=False)
    op.create_index(op.f('ix_facilities_name'), 'facilities', ['name'], unique=False)
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('appointment_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('appointment_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_by', sa.Integer(), nullable=True),
    sa.Column('cancellation_reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cancelled_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_appointment_date'), 'appointments', ['appointment_date'], unique=False)
    op.create_index(op.f('ix_appointments_facility_id'), 'appointments', ['facility_id'], unique=False)
    op.create_index(op.f('ix_appointments_id'), 'appointments', ['id'], unique=False)
    op.create_index(op.f('ix_appointments_patient_id'), 'appointments', ['patient_id'], unique=False)
    op.create_index(op.f('ix_appointments_provider_id'), 'appointments', ['provider_id'], unique=False)
    op.create_index(op.f('ix_appointments_status'), 'appointments', ['status'], unique=False)
    op.create_table('queue_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('appointment_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('facility_id', sa.UUID(), nullable=False),
    sa.Column('queue_date', sa.Date(), nullable=False),
    sa.Column('queue_number', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consultation_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_queue_entries_appointment_id'), 'queue_entries', ['appointment_id'], unique=True)
    op.create_index(op.f('ix_queue_entries_facility_id'), 'queue_entries', ['facility_id'], unique=False)
    op.create_index(op.f('ix_queue_entries_id'), 'queue_entries', ['id'], unique=False)
    op.create_index(op.f('ix_queue_entries_patient_id'), 'queue_entries', ['patient_id'], unique=False)
    op.create_index(op.f('ix_queue_entries_queue_date'), 'queue_entries', ['queue_date'], unique=False)
    op.create_index(op.f('ix_queue_entries_status'), 'queue_entries', ['status'], unique=False)
    op.add_column('patients', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'patients', ['user_id'])
    op.create_foreign_key(None, 'patients', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('facility_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'users', 'facilities', ['facility_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'facility_id')
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_constraint(None, 'patients', type_='unique')
    op.drop_column('patients', 'user_id')
    op.drop_index(op.f('ix_queue_entries_status'), table_name='queue_entries')
    op.drop_index(op.f('ix_queue_entries_queue_date'), table_name='queue_entries')
    op.drop_index(op.f('ix_queue_entries_patient_id'), table_name='queue_entries')
    op.drop_index(op.f('ix_queue_entries_id'), table_name='queue_entries')
    op.drop_index(op.f('ix_queue_entries_facility_id'), table_name='queue_entries')
    op.drop_index(op.f('ix_queue_entries_appointment_id'), table_name='queue_entries')
    op.drop_table('queue_entries')
    op.drop_index(op.f('ix_appointments_status'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_provider_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_patient_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_facility_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_appointment_date'), table_name='appointments')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_facilities_name'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_id'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_facility_code'), table_name='facilities')
    op.drop_table('facilities')
    # ### end Alembic commands ###
